name: Deploy AMI Frontend App
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Dispatch reason'
        required: false
        default: 'NA'
jobs:
  deploy:
    environment: ami-frontend-app
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Build
        env:
          TURNSTILE_SECRET_KEY: ${{secrets.TURNSTILE_SECRET_KEY}}
          PUBLIC_TURNSTILE_SITE_KEY: ${{secrets.PUBLIC_TURNSTILE_SITE_KEY}}
          PUBLIC_MODE: PROD
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
          TO_EMAIL: ${{secrets.TO_EMAIL}}
          PUBLIC_PAYPAL_CLIENT_ID: ${{secrets.PUBLIC_PAYPAL_CLIENT_ID}}
        run: |
          npm install
          CLOUDFLARE_DEPLOY=1 npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=adonai-ministries-frontend
